#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PROTECTED_BRANCHES="^(master|develop)"
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = $PROTECTED_BRANCHES  ]; then
  echo "You can't commit directly to main/master branch"
  exit 1
fi


npm run lint
npm run test



