name: Test Code
on:
  push:
    branches-ignore:
      - main
      - master
jobs:
  test-code:
    name: "validate code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test

  deploy:
    needs: test-code
    name: "Deploy to QA"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Change Home Page
        run: node changeHP.js

      - name: Build
        run: CI=false npm run build

      - name: deploy to qa
        run: netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --dir=./build

  PullRequest:
    needs: deploy
    name: "Create pull request"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pr
        uses: medlypharmacy/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
