name: Test Code
on:
  push:
    branches-ignore:
      - main
jobs:
  test-code:
    name: "validate code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test
      - name: Change Home Page
        run: node changeHP.js

  deploy:
    needs: test-code
    name: "Deploy to QA"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          install_command: npm run build
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
